"""fixed date constraint

Revision ID: 031410a8b59c
Revises: b9f6b07bdc6b
Create Date: 2026-07-14 17:30:25.583735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '031410a8b59c'
down_revision: Union[str, Sequence[str], None] = 'b9f6b07bdc6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_postings', 'pub_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('job_postings', 'expiry_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_postings', 'expiry_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('job_postings', 'pub_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
