"""add review_status column to job_postings

Revision ID: 035cb6fd05c2
Revises: 031410a8b59c
Create Date: 2026-07-20 12:42:29.354692

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "035cb6fd05c2"
down_revision: Union[str, Sequence[str], None] = "031410a8b59c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    review_status_enum = sa.Enum("new", "accepted", "declined", name="review_status")
    review_status_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "job_postings",
        sa.Column(
            "review_status", review_status_enum, server_default="new", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("job_postings", "review_status")
    sa.Enum(name="review_status").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
